container:
  image: google/dart

task:
  pub_cache:
    folder: $HOME/.pub-cache
    fingerprint_script: sha256sum pubspec.yaml
    populate_script: pub get

  resolve_dependecies:
    get_script: pub get

  matrix:
    - name: Test
      container:
        image: google/dart
      test_script: pub run test
