container:
  image: google/dart

task:
  pub_cache:
    folder: $HOME/.pub-cache
    fingerprint_script: sha256sum pubspec.yaml
    populate_script: pub get

  resolve_deps_script: pub get

  matrix:
    - name: Test
      container:
        image: google/dart

      env:
        CODECOV_TOKEN: ENCRYPTED[24bf9b1ff555cec978552f640cdfcd49500f32b17649e356ab9758f6172ac7ecbe1de3ed8cccaf4b8678d1b510695a67]

      test_script: pub run test
      cov_script: ./tool/coverage.sh
