name: test_cirrus
version: 0.1.0
author: Roman Vanesyan <romain.vanesyan@gmail.com>
license: BSD-3-Clause

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  meta: ^1.1.7

dev_dependencies:
  test: ^1.5.3
